#! /usr/bin/env bash
if  echo $OSTYPE | grep darwin > /dev/null ; then
  cat | sed -E -e 's/(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}/took_out_a_guid/g'
else
  cat | sed -r -e 's/(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}/took_out_a_guid/g'
fi
