#! /usr/bin/env bash
set -e
KEY=$(uuid)
curl -s ${KVSTORE_SERVICE_ROOT}/${KEY} --data '{"one":1,"two":2,"name":"pants"}' -H 'Content-Type: application/json'
# need to make sure it comes back in a JSON parsable format, hence the pipe to jq
curl -s ${KVSTORE_SERVICE_ROOT}/${KEY} | jq "."
curl --head -s ${KVSTORE_SERVICE_ROOT}/${KEY} | grep 'Content-Type' 
