#! /usr/bin/env bash
set -e
KEY=$(uuid)
# should not be there, expect 404
curl -s --write-out '%{http_code}\n' ${KVSTORE_SERVICE_ROOT}/${KEY} 
# put it in
curl -s ${KVSTORE_SERVICE_ROOT}/${KEY} --data '{"one":1,"two":2,"name":"pants"}' -H 'Content-Type: application/json' # 
# now we should get a 200
curl -s --write-out '%{http_code}\n' ${KVSTORE_SERVICE_ROOT}/${KEY} 
# an we'll delete it
curl -s -X DELETE curl -s ${KVSTORE_SERVICE_ROOT}/${KEY} 
# should not be there, expect 404
curl -s --write-out '%{http_code}\n' ${KVSTORE_SERVICE_ROOT}/${KEY} 
